name: Tests

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install node modules
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run contract tests
        id: run-tests
        run: npx hardhat test
        env:
          GOERLI_PROVIDER: ${{ secrets.GOERLI_PROVIDER }}